openapi: 3.0.3
info:
  title: Diver API
  description: The second version of Diver API documentation.
  version: 2.0.0
  contact:
    name: SeungBin Kim
    email: seungbin0508@gmail.com
    url: https://github.com/seungbin0508
servers:
  - url: "http://localhost:3000/v2"
paths:
  /users:
  /books:
    get:
      tags: ["Book"]
  /books/:book_id:
    get:
      tags: ["Book"]
  /books/bestsellers:
    get:
      tags: ["Book"]
  /feeds:
    get:
      tags: ["Feed"]
      summary: Gets feeds
      description: Based on query, client can retreive one of recent, popular or social feeds.
      parameters:
        - in: query
          name: order
          schema:
            type: string
            enum: ["recent", "popular", "social"]
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feeds"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /follows/followers/:user_id:
    get:
      tags: ["Follower"]
      summary: Gets array of users following given user ID
      parameters:
        - $ref: "#/components/schemas/user_id"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
                  # Array of basic user information with user image, nickname and user_id
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /follows/followees/:user_id:
    get:
      tags: ["Follower"]
      summary: Gets array of users whom given user ID follows
      parameters:
        - $ref: "#/components/schemas/user_id"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
                  # Duplicate exists at getting follower list. Should be replaced with reference
    post:
      tags: ["Follower"]
      responses:
        '403':
          $ref: "#/components/responses/Forbidden"
    delete:
      tags: ["Follower"]
      responses:
        '403':
          $ref: "#/components/responses/Forbidden"
  /collections:
  /suggestions:
  /search:
components:
  responses:
    Forbidden:
      description: User ID in path and session token don't match.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"