openapi: 3.0.3
info:
  title: Diver API
  description: The second version of Diver API documentation.
  version: 2.0.0
  contact:
    name: SeungBin Kim
    email: seungbin0508@gmail.com
    url: https://github.com/seungbin0508
servers:
  - url: "http://localhost:3000/v2"
paths:
  /users:
  /books:
    get:
      tags: ["Book"]
  /books/:book_id:
    get:
      tags: ["Book"]
  /books/bestsellers:
    get:
      tags: ["Book"]
  /feeds:
  /follows:
  /collections:
  /suggestions:
  /search:
